name: Deploy VitePress to GitHub Pages
on:
  push:
    branches:
      - main # 根据你的实际默认分支进行修改，这里假设是main分支触发工作流
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 确保能获取完整的提交历史，某些情况可能需要

      # 设置Node.js环境，这里指定Node.js版本为20，你可按需调整
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm # 使用npm缓存，加快依赖安装速度，也可按需换为pnpm/yarn等

      # 设置PATH环境变量，确保能找到vitepress等命令
      - name: Set up PATH
        run: echo "PATH=$PATH:$(pwd)/node_modules/.bin" >> $GITHUB_ENV

      # 安装项目依赖
      - name: Install dependencies
        run: npm ci

      # 构建VitePress项目
      - name: Build with VitePress
        run: npm run docs:build

      # 上传构建产物作为 artifacts，方便后续部署步骤使用
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

      # 配置GitHub Pages相关设置，并进行部署
      - name: Configure and Deploy
        uses: actions/deploy-pages@v4
